name: Submit Extension

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  cache: "yarn"

            - run: yarn install
            - run: npx grunt build --clientId=${{ secrets.FEEDLY_CLIENT_ID }} --clientSecret=${{ secrets.FEEDLY_CLIENT_SECRET }} --browser=chrome
            - run: npx grunt build --clientId=${{ secrets.FEEDLY_CLIENT_ID }} --clientSecret=${{ secrets.FEEDLY_CLIENT_SECRET }} --browser=firefox
            - run: npx grunt build --clientId=${{ secrets.FEEDLY_CLIENT_ID }} --clientSecret=${{ secrets.FEEDLY_CLIENT_SECRET }} --browser=opera

            - name: Setup Chrome
              uses: browser-actions/setup-chrome@latest
              with:
                  chrome-version: latest

            - name: Browser Plugin Publish
              env:
                  PUPPETEER_EXECUTABLE_PATH: /opt/hostedtoolcache/chromium/latest/x64/chrome
              uses: plasmo-corp/bpp@v1
              with:
                  keys: ${{ secrets.SUBMIT_KEYS }}
